exasol backend
Nicoretti/ibis pull request #1
Opened 2023-09-14 10:23 UTC by Nicoretti

- Add exasol db for testing
- Add exasol to pyproject.toml
- Add structure and package for exasol backend
- Add basic implementation of exasol backend
- Add basic documentation for exasol backend
- Add development notes

2023-09-14 13:54 UTC, tkilias requested changes

2023-09-14 13:54 UTC, tkilias commented on docs/backends/exasol.qmd
> +Install Ibis and dependencies for the Druid backend:
```suggestion
Install Ibis and dependencies for the Exasol backend:
```

2023-09-14 13:54 UTC, tkilias commented on ibis/backends/exasol/__init__.py
> +    supports_create_or_replace = False
hm, for many things we support create or replace, we probably need to investigate what exactly this parameter means

2023-09-14 13:54 UTC, tkilias commented on ibis/backends/exasol/__init__.py
> +    supports_python_udfs = False
uh, could be interesting later on

2023-09-14 13:54 UTC, tkilias commented on ibis/backends/exasol/__init__.py
> +        """TBD."""
don't forget this

2023-09-14 13:54 UTC, tkilias commented on ibis/backends/exasol/compiler.py
> +    support_values_syntax_in_select = False
this we probably need to check as well, might be supported

2023-09-14 13:54 UTC, tkilias commented on ibis/backends/exasol/tests/conftest.py
> +class Option(Generic[T]):
Looks familiar

2023-09-14 13:54 UTC, tkilias commented on ibis/backends/exasol/tests/conftest.py
> +    supports_arrays = True
I think, we don't support arrays

2023-09-14 13:54 UTC, tkilias commented on ibis/backends/exasol/tests/conftest.py
> +    supports_json = True
this depends what it means, we have functions on varchar with json, but no native json type

2023-09-14 13:54 UTC, tkilias commented on ibis/backends/exasol/tests/conftest.py
> +            binary = "/usr/opt/EXASuite-7/EXASolution-7.1.22/bin/Console/exaplus"
why do you try first a hardcoded path?

2023-09-14 13:54 UTC, tkilias commented on ibis/backends/exasol/tests/conftest.py
> +            # TODO: custom generated certificate,
that is quite a lot of effort to add a custom generated certificate

2023-10-05 12:04 UTC, Nicoretti commented on ibis/backends/exasol/tests/conftest.py
> +            binary = "/usr/opt/EXASuite-7/EXASolution-7.1.22/bin/Console/exaplus"
because it have been significantly faster

2023-10-05 12:05 UTC, Nicoretti commented on ibis/backends/exasol/tests/conftest.py
> +            # TODO: custom generated certificate,
Don't recall when i have put it there, for testing it can be skipped for now. Good point.

2023-11-17 10:53 UTC, closed without merging